In [14]:
from pymongo import MongoClient

In [15]:
uri = "mongodb+srv://rahulyadavv7000:Yadavrahul7000@cluster0.rtewdtg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri)

In [16]:
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [17]:
#this is my database
mydb = client["mydatabase"]

In [18]:
mycol = mydb["myfirstcollection"]

In [19]:
myfirstrecord = {"fname": "rahul", "lname":"yadav", "address": "delhi"}

In [20]:
mycol.insert_one(myfirstrecord)

InsertOneResult(ObjectId('65fa247176dd4549cca1ea23'), acknowledged=True)

In [21]:
mysecondrecord = {"fname": "adeeb", "lname":"saifi", "address": "delhi"}

In [22]:
mycol.insert_one(mysecondrecord)

InsertOneResult(ObjectId('65fa247176dd4549cca1ea24'), acknowledged=True)

In [23]:
client.list_database_names()

['mydatabase', 'sample_mflix', 'admin', 'local']

In [24]:
multiplerecords = [

    {"fname": "ankit", "lname":"kumar", "address": "delhi"},
    {"fname": "saqib", "lname":"choudhary", "address": "delhi"}, 
    {"fname":"anish", "lname":"kumar", "address": "delhi"},
    {"fname":"munna", "lname":"michael", "address": "delhi"},
    {"fname":"sonu", "lname":"yadav", "address": "delhi"},
     
]

In [25]:
x = mycol.insert_many(multiplerecords)

In [26]:
x.inserted_ids

[ObjectId('65fa247176dd4549cca1ea25'),
 ObjectId('65fa247176dd4549cca1ea26'),
 ObjectId('65fa247176dd4549cca1ea27'),
 ObjectId('65fa247176dd4549cca1ea28'),
 ObjectId('65fa247176dd4549cca1ea29')]

In [27]:
for x in mycol.find():
    print(x)

{'_id': ObjectId('65fa06a4691eb9e93dbc7c1b'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa07d2691eb9e93dbc7c1c'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1d'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1e'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1f'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c20'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c21'), 'fname': 'abhishek', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea23'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea24'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea25'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea26'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea27'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea28'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea29'), 'fname': 'sonu', 'lname': 'yadav', 'address': 'delhi'}

In [28]:
mycol.find_one({"name":"rahul"})

In [29]:
for x in mycol.find({"lname":"yadav"}):
    print(x)

{'_id': ObjectId('65fa06a4691eb9e93dbc7c1b'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c21'), 'fname': 'abhishek', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea23'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea29'), 'fname': 'sonu', 'lname': 'yadav', 'address': 'delhi'}

In [30]:
for x in mycol.find().sort("fname"):
    print(x)

{'_id': ObjectId('65fa0c9e691eb9e93dbc7c21'), 'fname': 'abhishek', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa07d2691eb9e93dbc7c1c'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea24'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1f'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea27'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1d'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea25'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c20'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea28'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa06a4691eb9e93dbc7c1b'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea23'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1e'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea26'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea29'), 'fname': 'sonu', 'lname': 'yadav', 'address': 'delhi'}

In [31]:
for x in mycol.find().sort("fname", -1):
    print(x)

{'_id': ObjectId('65fa247176dd4549cca1ea29'), 'fname': 'sonu', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1e'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea26'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa06a4691eb9e93dbc7c1b'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea23'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c20'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea28'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1d'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea25'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1f'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea27'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa07d2691eb9e93dbc7c1c'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea24'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c21'), 'fname': 'abhishek', 'lname': 'yadav', 'address': 'delhi'}

In [32]:
for x in mycol.find().limit(4):
    print(x)

{'_id': ObjectId('65fa06a4691eb9e93dbc7c1b'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa07d2691eb9e93dbc7c1c'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1d'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1e'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}

In [33]:
myquery = {"fname" : "sonu"}
newvalue = {"$set":{"fname":"abhishek"}}

In [34]:
mycol.update_one(myquery, newvalue)

UpdateResult({'n': 1, 'electionId': ObjectId('7fffffff0000000000000003'), 'opTime': {'ts': Timestamp(1710892148, 1), 't': 3}, 'nModified': 1, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1710892148, 1), 'signature': {'hash': b'$\x7f>D\x00\xba\xe3|\xab\x10{d\xba\xdc!\xe0zh\xcf*', 'keyId': 7348016481642217477}}, 'operationTime': Timestamp(1710892148, 1), 'updatedExisting': True}, acknowledged=True)

In [35]:
for x in mycol.find():
    print(x)

{'_id': ObjectId('65fa06a4691eb9e93dbc7c1b'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa07d2691eb9e93dbc7c1c'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1d'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1e'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c1f'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c20'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa0c9e691eb9e93dbc7c21'), 'fname': 'abhishek', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea23'), 'fname': 'rahul', 'lname': 'yadav', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea24'), 'fname': 'adeeb', 'lname': 'saifi', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea25'), 'fname': 'ankit', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea26'), 'fname': 'saqib', 'lname': 'choudhary', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea27'), 'fname': 'anish', 'lname': 'kumar', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea28'), 'fname': 'munna', 'lname': 'michael', 'address': 'delhi'}
{'_id': ObjectId('65fa247176dd4549cca1ea29'), 'fname': 'abhishek', 'lname': 'yadav', 'address': 'delhi'}

In [36]:
import pandas as pd

url = "https://raw.githubusercontent.com/ShapeLab/ZooidsCompositePhysicalizations/master/Zooid_Vis/bin/data/student-dataset.csv"
df = pd.read_csv(url)

print(df.head())

   id             name               nationality                 city  \
0   0        Kiana Lor                     China               Suzhou
1   1   Joshua Lonaker  United States of America        Santa Clarita
2   2    Dakota Blanco  United States of America              Oakland
3   3  Natasha Yarusso  United States of America        Castro Valley
4   4   Brooke Cazares                    Brazil  São José dos Campos

   latitude  longitude gender  ethnic.group  age  english.grade  math.grade  \
0     31.31     120.62      F           NaN   22            3.5         3.7
1     34.39    -118.54      M           NaN   22            2.9         3.2
2     37.80    -122.27      F           NaN   22            3.9         3.8
3     37.69    -122.09      F           NaN   20            3.3         2.8
4    -23.18     -45.88      F           NaN   21            3.7         2.6

   sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
0             3.1             1.0                 4                 4.0
1             3.6             5.0                 5                 4.0
2             3.2             5.0                 3                 3.0
3             3.2             5.0                 5                 2.0
4             3.4             1.0                 4                 4.0

   refletter.rating
0                 4
1                 5
2                 4
3                 4
4                 5

In [37]:
df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [38]:
df.columns

Index(['id', 'name', 'nationality', 'city', 'latitude', 'longitude', 'gender',
       'ethnic.group', 'age', 'english.grade', 'math.grade', 'sciences.grade',
       'language.grade', 'portfolio.rating', 'coverletter.rating',
       'refletter.rating'],
      dtype='object')

In [39]:
len(df.columns)

16

In [ ]:
#this is my database
mydb = client["mydatabase"]

In [40]:
mycol2 = mydb["googleplaystore"]

In [45]:
import json

json.loads(df.T.to_json())

{'0': {'id': 0,
  'name': 'Kiana Lor',
  'nationality': 'China',
  'city': 'Suzhou',
  'latitude': 31.31,
  'longitude': 120.62,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.5,
  'math.grade': 3.7,
  'sciences.grade': 3.1,
  'language.grade': 1.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '1': {'id': 1,
  'name': 'Joshua Lonaker',
  'nationality': 'United States of America',
  'city': 'Santa Clarita',
  'latitude': 34.39,
  'longitude': -118.54,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 2.9,
  'math.grade': 3.2,
  'sciences.grade': 3.6,
  'language.grade': 5.0,
  'portfolio.rating': 5,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '2': {'id': 2,
  'name': 'Dakota Blanco',
  'nationality': 'United States of America',
  'city': 'Oakland',
  'latitude': 37.8,
  'longitude': -122.27,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.9,
  'math.grade': 3.8,
  'sciences.grade': 3.2,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 3.0,
  'refletter.rating': 4},
 '3': {'id': 3,
  'name': 'Natasha Yarusso',
  'nationality': 'United States of America',
  'city': 'Castro Valley',
  'latitude': 37.69,
  'longitude': -122.09,
  'gender': 'F',
  'ethnic.group': None,
  'age': 20,
  'english.grade': 3.3,
  'math.grade': 2.8,
  'sciences.grade': 3.2,
  'language.grade': 5.0,
  'portfolio.rating': 5,
  'coverletter.rating': 2.0,
  'refletter.rating': 4},
 '4': {'id': 4,
  'name': 'Brooke Cazares',
  'nationality': 'Brazil',
  'city': 'São José dos Campos',
  'latitude': -23.18,
  'longitude': -45.88,
  'gender': 'F',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.7,
  'math.grade': 2.6,
  'sciences.grade': 3.4,
  'language.grade': 1.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '5': {'id': 5,
  'name': 'Rochelle Johnson',
  'nationality': 'United States of America',
  'city': 'Indianapolis',
  'latitude': 39.77,
  'longitude': -86.16,
  'gender': 'F',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.4,
  'math.grade': 3.1,
  'sciences.grade': 3.7,
  'language.grade': 5.0,
  'portfolio.rating': 2,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '6': {'id': 6,
  'name': 'Joey Abreu',
  'nationality': 'China',
  'city': 'Shenyang',
  'latitude': 41.79,
  'longitude': 123.43,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.7,
  'math.grade': 3.9,
  'sciences.grade': 3.6,
  'language.grade': 2.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '7': {'id': 7,
  'name': 'Preston Suarez',
  'nationality': 'Brazil',
  'city': 'São Paulo',
  'latitude': -23.47,
  'longitude': -46.67,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.8,
  'math.grade': 3.7,
  'sciences.grade': 3.6,
  'language.grade': 2.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '8': {'id': 8,
  'name': 'Lee Dong',
  'nationality': 'Philippines',
  'city': 'Manila',
  'latitude': 14.6,
  'longitude': 120.98,
  'gender': 'F',
  'ethnic.group': None,
  'age': 24,
  'english.grade': 3.9,
  'math.grade': 3.6,
  'sciences.grade': 3.2,
  'language.grade': 2.0,
  'portfolio.rating': 4,
  'coverletter.rating': 3.0,
  'refletter.rating': 5},
 '9': {'id': 9,
  'name': "Maa'iz al-Dia",
  'nationality': 'Turkey',
  'city': 'Istanbul',
  'latitude': 41.02,
  'longitude': 28.96,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 2.4,
  'math.grade': 2.8,
  'sciences.grade': 3.8,
  'language.grade': 3.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '10': {'id': 10,
  'name': 'Maja Nicholson',
  'nationality': 'United States of America',
  'city': 'Dallas',
  'latitude': 32.78,
  'longitude': -96.8,
  'gender': 'F',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.4,
  'math.grade': 3.5,
  'sciences.grade': 3.2,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 2.0,
  'refletter.rating': 5},
 '11': {'id': 11,
  'name': 'Sasha Jansen',
  'nationality': 'United States of America',
  'city': 'Chicago',
  'latitude': 41.85,
  'longitude': -87.65,
  'gender': 'F',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 1.7,
  'math.grade': 4.0,
  'sciences.grade': 3.6,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '12': {'id': 12,
  'name': 'Alexander Sherman',
  'nationality': 'United States of America',
  'city': 'Omaha',
  'latitude': 41.26,
  'longitude': -95.94,
  'gender': 'M',
  'ethnic.group': None,
  'age': 20,
  'english.grade': 3.8,
  'math.grade': 3.6,
  'sciences.grade': 3.9,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '13': {'id': 13,
  'name': 'Edgar Sanchez',
  'nationality': 'Mexico',
  'city': 'Tijuana',
  'latitude': 32.53,
  'longitude': -117.02,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.7,
  'math.grade': 3.5,
  'sciences.grade': 4.0,
  'language.grade': 4.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '14': {'id': 14,
  'name': 'Kolbi Strunk',
  'nationality': 'United States of America',
  'city': 'Mission Viejo',
  'latitude': 33.6,
  'longitude': -117.67,
  'gender': 'M',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.2,
  'math.grade': 3.9,
  'sciences.grade': 3.3,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 3.0,
  'refletter.rating': 4},
 '15': {'id': 15,
  'name': 'Brittany Sath',
  'nationality': 'Japan',
  'city': 'Tokyo',
  'latitude': 35.69,
  'longitude': 139.75,
  'gender': 'F',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 4.0,
  'math.grade': 3.9,
  'sciences.grade': 3.7,
  'language.grade': 3.0,
  'portfolio.rating': 5,
  'coverletter.rating': 3.0,
  'refletter.rating': 5},
 '16': {'id': 16,
  'name': 'Meggan Smith',
  'nationality': 'United States of America',
  'city': 'Los Angeles',
  'latitude': 34.05,
  'longitude': -118.24,
  'gender': 'F',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 2.9,
  'math.grade': 3.4,
  'sciences.grade': 3.6,
  'language.grade': 5.0,
  'portfolio.rating': 2,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '17': {'id': 17,
  'name': 'Ericka Arreola',
  'nationality': 'Mexico',
  'city': 'Mexico',
  'latitude': 19.43,
  'longitude': -99.14,
  'gender': 'other',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.1,
  'math.grade': 3.5,
  'sciences.grade': 2.8,
  'language.grade': 4.0,
  'portfolio.rating': 4,
  'coverletter.rating': 3.0,
  'refletter.rating': 4},
 '18': {'id': 18,
  'name': 'David Pulc',
  'nationality': 'Canada',
  'city': 'Toronto',
  'latitude': 43.67,
  'longitude': -79.42,
  'gender': 'M',
  'ethnic.group': None,
  'age': 24,
  'english.grade': 3.9,
  'math.grade': 2.9,
  'sciences.grade': 4.0,
  'language.grade': 5.0,
  'portfolio.rating': 5,
  'coverletter.rating': 4.0,
  'refletter.rating': 2},
 '19': {'id': 19,
  'name': 'Kyle Luckey',
  'nationality': 'United States of America',
  'city': 'Moreno Valley',
  'latitude': 33.94,
  'longitude': -117.23,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.7,
  'math.grade': 3.9,
  'sciences.grade': 3.4,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '20': {'id': 20,
  'name': 'Rojesh Her',
  'nationality': 'Japan',
  'city': 'Tokyo',
  'latitude': 35.69,
  'longitude': 139.75,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.8,
  'math.grade': 3.6,
  'sciences.grade': 3.6,
  'language.grade': 2.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 3},
 '21': {'id': 21,
  'name': 'David Weber',
  'nationality': 'China',
  'city': 'Peking',
  'latitude': 39.93,
  'longitude': 116.39,
  'gender': 'M',
  'ethnic.group': None,
  'age': 20,
  'english.grade': 3.9,
  'math.grade': 3.9,
  'sciences.grade': 3.9,
  'language.grade': 2.0,
  'portfolio.rating': 3,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '22': {'id': 22,
  'name': 'Rachel Jambor',
  'nationality': 'United States of America',
  'city': 'Chicago',
  'latitude': 41.85,
  'longitude': -87.65,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.6,
  'math.grade': 3.6,
  'sciences.grade': 3.9,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '23': {'id': 23,
  'name': "Mus'ab al-Moustafa",
  'nationality': 'Pakistan',
  'city': 'Rawalpindi',
  'latitude': 33.6,
  'longitude': 73.07,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.8,
  'math.grade': 3.9,
  'sciences.grade': 3.8,
  'language.grade': 2.0,
  'portfolio.rating': 2,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '24': {'id': 24,
  'name': 'Sila Nguyen',
  'nationality': 'China',
  'city': 'Hebi',
  'latitude': 35.9,
  'longitude': 114.19,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 2.8,
  'math.grade': 3.5,
  'sciences.grade': 3.5,
  'language.grade': 4.0,
  'portfolio.rating': 5,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '25': {'id': 25,
  'name': 'Samantha Hicks',
  'nationality': 'United States of America',
  'city': 'Santa Barbara',
  'latitude': 34.42,
  'longitude': -119.7,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.7,
  'math.grade': 3.7,
  'sciences.grade': 3.8,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '26': {'id': 26,
  'name': 'Angela Harding',
  'nationality': 'United States of America',
  'city': 'Manteca',
  'latitude': 37.8,
  'longitude': -121.22,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.1,
  'math.grade': 2.9,
  'sciences.grade': 3.2,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '27': {'id': 27,
  'name': 'Brandon Barbour',
  'nationality': 'United States of America',
  'city': 'South Hill',
  'latitude': 47.14,
  'longitude': -122.27,
  'gender': 'M',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.9,
  'math.grade': 3.7,
  'sciences.grade': 3.3,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '28': {'id': 28,
  'name': 'Reilly Wagar',
  'nationality': 'United States of America',
  'city': 'Modesto',
  'latitude': 37.64,
  'longitude': -121.0,
  'gender': 'F',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.4,
  'math.grade': 3.2,
  'sciences.grade': 3.7,
  'language.grade': 5.0,
  'portfolio.rating': 5,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '29': {'id': 29,
  'name': 'Victoria Ibarra',
  'nationality': 'Dominican Republic',
  'city': 'Santo Domingo',
  'latitude': 18.47,
  'longitude': -69.9,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.4,
  'math.grade': 3.8,
  'sciences.grade': 4.0,
  'language.grade': 4.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '30': {'id': 30,
  'name': 'Dakota Wirth',
  'nationality': 'United States of America',
  'city': 'Sacramento',
  'latitude': 38.58,
  'longitude': -121.49,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.4,
  'math.grade': 3.9,
  'sciences.grade': 3.6,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '31': {'id': 31,
  'name': 'Lauren Klocker',
  'nationality': 'United States of America',
  'city': 'Los Angeles',
  'latitude': 34.05,
  'longitude': -118.24,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 2.3,
  'math.grade': 3.9,
  'sciences.grade': 3.8,
  'language.grade': 5.0,
  'portfolio.rating': 5,
  'coverletter.rating': 3.0,
  'refletter.rating': 4},
 '32': {'id': 32,
  'name': 'Michael Benson',
  'nationality': 'United States of America',
  'city': 'Phoenix',
  'latitude': 33.45,
  'longitude': -112.07,
  'gender': 'M',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.8,
  'math.grade': 3.7,
  'sciences.grade': 3.7,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 3},
 '33': {'id': 33,
  'name': 'Sean Rozga',
  'nationality': 'United States of America',
  'city': 'Los Angeles',
  'latitude': 34.05,
  'longitude': -118.24,
  'gender': 'M',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.4,
  'math.grade': 3.8,
  'sciences.grade': 3.6,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '34': {'id': 34,
  'name': 'Cody Vermeylen',
  'nationality': 'United States of America',
  'city': 'Detroit',
  'latitude': 42.33,
  'longitude': -83.05,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.3,
  'math.grade': 3.8,
  'sciences.grade': 3.5,
  'language.grade': 5.0,
  'portfolio.rating': 2,
  'coverletter.rating': 3.0,
  'refletter.rating': 4},
 '35': {'id': 35,
  'name': 'Kinaana al-Jamail',
  'nationality': 'India',
  'city': 'Kanpur',
  'latitude': 26.47,
  'longitude': 80.35,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.3,
  'math.grade': 3.8,
  'sciences.grade': 3.7,
  'language.grade': 3.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '36': {'id': 36,
  'name': 'Daniel Garcia',
  'nationality': 'Peru',
  'city': 'Lima',
  'latitude': -12.05,
  'longitude': -77.05,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.7,
  'math.grade': 3.1,
  'sciences.grade': 3.0,
  'language.grade': 3.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '37': {'id': 37,
  'name': 'Katrina Saito',
  'nationality': 'Japan',
  'city': 'Tokyo',
  'latitude': 35.69,
  'longitude': 139.75,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.8,
  'math.grade': 4.0,
  'sciences.grade': 3.7,
  'language.grade': 4.0,
  'portfolio.rating': 5,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '38': {'id': 38,
  'name': 'Joshua Galloway',
  'nationality': 'United States of America',
  'city': 'New York',
  'latitude': 40.71,
  'longitude': -74.01,
  'gender': 'M',
  'ethnic.group': None,
  'age': 24,
  'english.grade': 3.3,
  'math.grade': 3.3,
  'sciences.grade': 3.6,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '39': {'id': 39,
  'name': 'Aylin Mendoza',
  'nationality': 'Mexico',
  'city': 'Mexico',
  'latitude': 19.43,
  'longitude': -99.14,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.0,
  'math.grade': 2.3,
  'sciences.grade': 3.9,
  'language.grade': 4.0,
  'portfolio.rating': 2,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '40': {'id': 40,
  'name': 'Sharon Fyfe',
  'nationality': 'United States of America',
  'city': 'Los Angeles',
  'latitude': 34.05,
  'longitude': -118.24,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.7,
  'math.grade': 3.0,
  'sciences.grade': 3.8,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '41': {'id': 41,
  'name': 'Afnaan el-Mohammed',
  'nationality': 'India',
  'city': 'New Delhi',
  'latitude': 28.6,
  'longitude': 77.2,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 1.7,
  'math.grade': 3.5,
  'sciences.grade': 3.9,
  'language.grade': 2.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '42': {'id': 42,
  'name': 'Jesse Williams',
  'nationality': 'Russian Federation',
  'city': 'Moscow',
  'latitude': 55.75,
  'longitude': 37.62,
  'gender': 'F',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.9,
  'math.grade': 3.4,
  'sciences.grade': 2.6,
  'language.grade': 4.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '43': {'id': 43,
  'name': 'Kenny Fukushima',
  'nationality': 'Japan',
  'city': 'Tokyo',
  'latitude': 35.69,
  'longitude': 139.75,
  'gender': 'M',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.9,
  'math.grade': 2.9,
  'sciences.grade': 3.3,
  'language.grade': 4.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '44': {'id': 44,
  'name': 'Tawnie Glaisher',
  'nationality': 'United States of America',
  'city': 'Fremont',
  'latitude': 37.55,
  'longitude': -121.99,
  'gender': 'F',
  'ethnic.group': None,
  'age': 24,
  'english.grade': 3.4,
  'math.grade': 3.2,
  'sciences.grade': 3.8,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '45': {'id': 45,
  'name': 'Britany Stevens',
  'nationality': 'United States of America',
  'city': 'Lafayette',
  'latitude': 37.89,
  'longitude': -122.12,
  'gender': 'F',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 3.6,
  'math.grade': 3.3,
  'sciences.grade': 3.5,
  'language.grade': 5.0,
  'portfolio.rating': 3,
  'coverletter.rating': 3.0,
  'refletter.rating': 3},
 '46': {'id': 46,
  'name': 'Alan Trinh',
  'nationality': 'Japan',
  'city': 'Tokyo',
  'latitude': 35.69,
  'longitude': 139.75,
  'gender': 'M',
  'ethnic.group': None,
  'age': 20,
  'english.grade': 2.8,
  'math.grade': 3.1,
  'sciences.grade': 3.8,
  'language.grade': 4.0,
  'portfolio.rating': 3,
  'coverletter.rating': 4.0,
  'refletter.rating': 5},
 '47': {'id': 47,
  'name': 'Zoe Kern',
  'nationality': 'United States of America',
  'city': 'West Jordan',
  'latitude': 40.61,
  'longitude': -111.94,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 2.1,
  'math.grade': 4.0,
  'sciences.grade': 3.4,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '48': {'id': 48,
  'name': 'Sidney Beavers',
  'nationality': 'United States of America',
  'city': 'Los Angeles',
  'latitude': 34.05,
  'longitude': -118.24,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 2.3,
  'math.grade': 2.8,
  'sciences.grade': 3.5,
  'language.grade': 5.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '49': {'id': 49,
  'name': 'Miriam Aguilar',
  'nationality': 'Mexico',
  'city': 'Mexicali',
  'latitude': 32.65,
  'longitude': -115.47,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.6,
  'math.grade': 3.8,
  'sciences.grade': 2.8,
  'language.grade': 2.0,
  'portfolio.rating': 4,
  'coverletter.rating': 4.0,
  'refletter.rating': 4},
 '50': {'id': 50,
  'name': 'Issac Mata',
  'nationality': 'Mexico',
  'city': 'Tehuacán',
  'latitude': 18.45,
  'longitude': -97.38,
  'gender': 'M',
  'ethnic.group': None,
  'age': 23,
  'english.grade': 2.4,
  'math.grade': 3.1,
  'sciences.grade': 2.7,
  'language.grade': 1.0,
  'portfolio.rating': 5,
  'coverletter.rating': 5.0,
  'refletter.rating': 4},
 '51': {'id': 51,
  'name': 'Hannah Uren',
  'nationality': 'United States of America',
  'city': 'Los Angeles',
  'latitude': 34.05,
  'longitude': -118.24,
  'gender': 'F',
  'ethnic.group': None,
  'age': 22,
  'english.grade': 3.2,
  'math.grade': 2.2,
  'sciences.grade': 3.5,
  'language.grade': 5.0,
  'portfolio.rating': 5,
  'coverletter.rating': 3.0,
  'refletter.rating': 5},
 '52': {'id': 52,
  'name': 'Zachary Bradley',
  'nationality': 'Spain',
  'city': 'Madrid',
  'latitude': 40.41,
  'longitude': -3.69,
  'gender': 'M',
  'ethnic.group': None,
  'age': 21,
  'english.grade': 3.5,
  'math.grade': 3.5,
  'sciences.grade': 3.4,
  'language.grade': 2.0,
  'portfolio.rating': 3,
  'coverletter.rating': 5.0,
  'refletter.rating': 5},
 '53': {'id': 53,

In [48]:
#list of records
mycsvfile = list(json.loads(df.T.to_json()).values())

In [49]:
mycol2.insert_many(mycsvfile)

InsertManyResult([ObjectId('65fa280976dd4549cca1ea2a'), ObjectId('65fa280976dd4549cca1ea2b'), ObjectId('65fa280976dd4549cca1ea2c'), ObjectId('65fa280976dd4549cca1ea2d'), ObjectId('65fa280976dd4549cca1ea2e'), ObjectId('65fa280976dd4549cca1ea2f'), ObjectId('65fa280976dd4549cca1ea30'), ObjectId('65fa280976dd4549cca1ea31'), ObjectId('65fa280976dd4549cca1ea32'), ObjectId('65fa280976dd4549cca1ea33'), ObjectId('65fa280976dd4549cca1ea34'), ObjectId('65fa280976dd4549cca1ea35'), ObjectId('65fa280976dd4549cca1ea36'), ObjectId('65fa280976dd4549cca1ea37'), ObjectId('65fa280976dd4549cca1ea38'), ObjectId('65fa280976dd4549cca1ea39'), ObjectId('65fa280976dd4549cca1ea3a'), ObjectId('65fa280976dd4549cca1ea3b'), ObjectId('65fa280976dd4549cca1ea3c'), ObjectId('65fa280976dd4549cca1ea3d'), ObjectId('65fa280976dd4549cca1ea3e'), ObjectId('65fa280976dd4549cca1ea3f'), ObjectId('65fa280976dd4549cca1ea40'), ObjectId('65fa280976dd4549cca1ea41'), ObjectId('65fa280976dd4549cca1ea42'), ObjectId('65fa280976dd4549cca1ea43'), ObjectId('65fa280976dd4549cca1ea44'), ObjectId('65fa280976dd4549cca1ea45'), ObjectId('65fa280976dd4549cca1ea46'), ObjectId('65fa280976dd4549cca1ea47'), ObjectId('65fa280976dd4549cca1ea48'), ObjectId('65fa280976dd4549cca1ea49'), ObjectId('65fa280976dd4549cca1ea4a'), ObjectId('65fa280976dd4549cca1ea4b'), ObjectId('65fa280976dd4549cca1ea4c'), ObjectId('65fa280976dd4549cca1ea4d'), ObjectId('65fa280976dd4549cca1ea4e'), ObjectId('65fa280976dd4549cca1ea4f'), ObjectId('65fa280976dd4549cca1ea50'), ObjectId('65fa280976dd4549cca1ea51'), ObjectId('65fa280976dd4549cca1ea52'), ObjectId('65fa280976dd4549cca1ea53'), ObjectId('65fa280976dd4549cca1ea54'), ObjectId('65fa280976dd4549cca1ea55'), ObjectId('65fa280976dd4549cca1ea56'), ObjectId('65fa280976dd4549cca1ea57'), ObjectId('65fa280976dd4549cca1ea58'), ObjectId('65fa280976dd4549cca1ea59'), ObjectId('65fa280976dd4549cca1ea5a'), ObjectId('65fa280976dd4549cca1ea5b'), ObjectId('65fa280976dd4549cca1ea5c'), ObjectId('65fa280976dd4549cca1ea5d'), ObjectId('65fa280976dd4549cca1ea5e'), ObjectId('65fa280976dd4549cca1ea5f'), ObjectId('65fa280976dd4549cca1ea60'), ObjectId('65fa280976dd4549cca1ea61'), ObjectId('65fa280976dd4549cca1ea62'), ObjectId('65fa280976dd4549cca1ea63'), ObjectId('65fa280976dd4549cca1ea64'), ObjectId('65fa280976dd4549cca1ea65'), ObjectId('65fa280976dd4549cca1ea66'), ObjectId('65fa280976dd4549cca1ea67'), ObjectId('65fa280976dd4549cca1ea68'), ObjectId('65fa280976dd4549cca1ea69'), ObjectId('65fa280976dd4549cca1ea6a'), ObjectId('65fa280976dd4549cca1ea6b'), ObjectId('65fa280976dd4549cca1ea6c'), ObjectId('65fa280976dd4549cca1ea6d'), ObjectId('65fa280976dd4549cca1ea6e'), ObjectId('65fa280976dd4549cca1ea6f'), ObjectId('65fa280976dd4549cca1ea70'), ObjectId('65fa280976dd4549cca1ea71'), ObjectId('65fa280976dd4549cca1ea72'), ObjectId('65fa280976dd4549cca1ea73'), ObjectId('65fa280976dd4549cca1ea74'), ObjectId('65fa280976dd4549cca1ea75'), ObjectId('65fa280976dd4549cca1ea76'), ObjectId('65fa280976dd4549cca1ea77'), ObjectId('65fa280976dd4549cca1ea78'), ObjectId('65fa280976dd4549cca1ea79'), ObjectId('65fa280976dd4549cca1ea7a'), ObjectId('65fa280976dd4549cca1ea7b'), ObjectId('65fa280976dd4549cca1ea7c'), ObjectId('65fa280976dd4549cca1ea7d'), ObjectId('65fa280976dd4549cca1ea7e'), ObjectId('65fa280976dd4549cca1ea7f'), ObjectId('65fa280976dd4549cca1ea80'), ObjectId('65fa280976dd4549cca1ea81'), ObjectId('65fa280976dd4549cca1ea82'), ObjectId('65fa280976dd4549cca1ea83'), ObjectId('65fa280976dd4549cca1ea84'), ObjectId('65fa280976dd4549cca1ea85'), ObjectId('65fa280976dd4549cca1ea86'), ObjectId('65fa280976dd4549cca1ea87'), ObjectId('65fa280976dd4549cca1ea88'), ObjectId('65fa280976dd4549cca1ea89'), ObjectId('65fa280976dd4549cca1ea8a'), ObjectId('65fa280976dd4549cca1ea8b'), ObjectId('65fa280976dd4549cca1ea8c'), ObjectId('65fa280976dd4549cca1ea8d'), ObjectId('65fa280976dd4549cca1ea8e'), ObjectId('65fa280976dd4549cca1ea8f'), ObjectId('65fa280976dd4549cca1ea90'), ObjectId('65fa280976dd4549cca1ea91'), ObjectId('65fa280976dd4549cca1ea92'), ObjectId('65fa280976dd4549cca1ea93'), ObjectId('65fa280976dd4549cca1ea94'), ObjectId('65fa280976dd4549cca1ea95'), ObjectId('65fa280976dd4549cca1ea96'), ObjectId('65fa280976dd4549cca1ea97'), ObjectId('65fa280976dd4549cca1ea98'), ObjectId('65fa280976dd4549cca1ea99'), ObjectId('65fa280976dd4549cca1ea9a'), ObjectId('65fa280976dd4549cca1ea9b'), ObjectId('65fa280976dd4549cca1ea9c'), ObjectId('65fa280976dd4549cca1ea9d'), ObjectId('65fa280976dd4549cca1ea9e'), ObjectId('65fa280976dd4549cca1ea9f'), ObjectId('65fa280976dd4549cca1eaa0'), ObjectId('65fa280976dd4549cca1eaa1'), ObjectId('65fa280976dd4549cca1eaa2'), ObjectId('65fa280976dd4549cca1eaa3'), ObjectId('65fa280976dd4549cca1eaa4'), ObjectId('65fa280976dd4549cca1eaa5'), ObjectId('65fa280976dd4549cca1eaa6'), ObjectId('65fa280976dd4549cca1eaa7'), ObjectId('65fa280976dd4549cca1eaa8'), ObjectId('65fa280976dd4549cca1eaa9'), ObjectId('65fa280976dd4549cca1eaaa'), ObjectId('65fa280976dd4549cca1eaab'), ObjectId('65fa280976dd4549cca1eaac'), ObjectId('65fa280976dd4549cca1eaad'), ObjectId('65fa280976dd4549cca1eaae'), ObjectId('65fa280976dd4549cca1eaaf'), ObjectId('65fa280976dd4549cca1eab0'), ObjectId('65fa280976dd4549cca1eab1'), ObjectId('65fa280976dd4549cca1eab2'), ObjectId('65fa280976dd4549cca1eab3'), ObjectId('65fa280976dd4549cca1eab4'), ObjectId('65fa280976dd4549cca1eab5'), ObjectId('65fa280976dd4549cca1eab6'), ObjectId('65fa280976dd4549cca1eab7'), ObjectId('65fa280976dd4549cca1eab8'), ObjectId('65fa280976dd4549cca1eab9'), ObjectId('65fa280976dd4549cca1eaba'), ObjectId('65fa280976dd4549cca1eabb'), ObjectId('65fa280976dd4549cca1eabc'), ObjectId('65fa280976dd4549cca1eabd'), ObjectId('65fa280976dd4549cca1eabe'), ObjectId('65fa280976dd4549cca1eabf'), ObjectId('65fa280976dd4549cca1eac0'), ObjectId('65fa280976dd4549cca1eac1'), ObjectId('65fa280976dd4549cca1eac2'), ObjectId('65fa280976dd4549cca1eac3'), ObjectId('65fa280976dd4549cca1eac4'), ObjectId('65fa280976dd4549cca1eac5'), ObjectId('65fa280976dd4549cca1eac6'), ObjectId('65fa280976dd4549cca1eac7'), ObjectId('65fa280976dd4549cca1eac8'), ObjectId('65fa280976dd4549cca1eac9'), ObjectId('65fa280976dd4549cca1eaca'), ObjectId('65fa280976dd4549cca1eacb'), ObjectId('65fa280976dd4549cca1eacc'), ObjectId('65fa280976dd4549cca1eacd'), ObjectId('65fa280976dd4549cca1eace'), ObjectId('65fa280976dd4549cca1eacf'), ObjectId('65fa280976dd4549cca1ead0'), ObjectId('65fa280976dd4549cca1ead1'), ObjectId('65fa280976dd4549cca1ead2'), ObjectId('65fa280976dd4549cca1ead3'), ObjectId('65fa280976dd4549cca1ead4'), ObjectId('65fa280976dd4549cca1ead5'), ObjectId('65fa280976dd4549cca1ead6'), ObjectId('65fa280976dd4549cca1ead7'), ObjectId('65fa280976dd4549cca1ead8'), ObjectId('65fa280976dd4549cca1ead9'), ObjectId('65fa280976dd4549cca1eada'), ObjectId('65fa280976dd4549cca1eadb'), ObjectId('65fa280976dd4549cca1eadc'), ObjectId('65fa280976dd4549cca1eadd'), ObjectId('65fa280976dd4549cca1eade'), ObjectId('65fa280976dd4549cca1eadf'), ObjectId('65fa280976dd4549cca1eae0'), ObjectId('65fa280976dd4549cca1eae1'), ObjectId('65fa280976dd4549cca1eae2'), ObjectId('65fa280976dd4549cca1eae3'), ObjectId('65fa280976dd4549cca1eae4'), ObjectId('65fa280976dd4549cca1eae5'), ObjectId('65fa280976dd4549cca1eae6'), ObjectId('65fa280976dd4549cca1eae7'), ObjectId('65fa280976dd4549cca1eae8'), ObjectId('65fa280976dd4549cca1eae9'), ObjectId('65fa280976dd4549cca1eaea'), ObjectId('65fa280976dd4549cca1eaeb'), ObjectId('65fa280976dd4549cca1eaec'), ObjectId('65fa280976dd4549cca1eaed'), ObjectId('65fa280976dd4549cca1eaee'), ObjectId('65fa280976dd4549cca1eaef'), ObjectId('65fa280976dd4549cca1eaf0'), ObjectId('65fa280976dd4549cca1eaf1'), ObjectId('65fa280976dd4549cca1eaf2'), ObjectId('65fa280976dd4549cca1eaf3'), ObjectId('65fa280976dd4549cca1eaf4'), ObjectId('65fa280976dd4549cca1eaf5'), ObjectId('65fa280976dd4549cca1eaf6'), ObjectId('65fa280976dd4549cca1eaf7'), ObjectId('65fa280976dd4549cca1eaf8'), ObjectId('65fa280976dd4549cca1eaf9'), ObjectId('65fa280976dd4549cca1eafa'), ObjectId('65fa280976dd4549cca1eafb'), ObjectId('65fa280976dd4549cca1eafc'), ObjectId('65fa280976dd4549cca1eafd'), ObjectId('65fa280976dd4549cca1eafe'), ObjectId('65fa280976dd4549cca1eaff'), ObjectId('65fa280976dd4549cca1eb00'), ObjectId('65fa280976dd4549cca1eb01'), ObjectId('65fa280976dd4549cca1eb02'), ObjectId('65fa280976dd4549cca1eb03'), ObjectId('65fa280976dd4549cca1eb04'), ObjectId('65fa280976dd4549cca1eb05'), ObjectId('65fa280976dd4549cca1eb06'), ObjectId('65fa280976dd4549cca1eb07'), ObjectId('65fa280976dd4549cca1eb08'), ObjectId('65fa280976dd4549cca1eb09'), ObjectId('65fa280976dd4549cca1eb0a'), ObjectId('65fa280976dd4549cca1eb0b'), ObjectId('65fa280976dd4549cca1eb0c'), ObjectId('65fa280976dd4549cca1eb0d'), ObjectId('65fa280976dd4549cca1eb0e'), ObjectId('65fa280976dd4549cca1eb0f'), ObjectId('65fa280976dd4549cca1eb10'), ObjectId('65fa280976dd4549cca1eb11'), ObjectId('65fa280976dd4549cca1eb12'), ObjectId('65fa280976dd4549cca1eb13'), ObjectId('65fa280976dd4549cca1eb14'), ObjectId('65fa280976dd4549cca1eb15'), ObjectId('65fa280976dd4549cca1eb16'), ObjectId('65fa280976dd4549cca1eb17'), ObjectId('65fa280976dd4549cca1eb18'), ObjectId('65fa280976dd4549cca1eb19'), ObjectId('65fa280976dd4549cca1eb1a'), ObjectId('65fa280976dd4549cca1eb1b'), ObjectId('65fa280976dd4549cca1eb1c'), ObjectId('65fa280976dd4549cca1eb1d'), ObjectId('65fa280976dd4549cca1eb1e'), ObjectId('65fa280976dd4549cca1eb1f'), ObjectId('65fa280976dd4549cca1eb20'), ObjectId('65fa280976dd4549cca1eb21'), ObjectId('65fa280976dd4549cca1eb22'), ObjectId('65fa280976dd4549cca1eb23'), ObjectId('65fa280976dd4549cca1eb24'), ObjectId('65fa280976dd4549cca1eb25'), ObjectId('65fa280976dd4549cca1eb26'), ObjectId('65fa280976dd4549cca1eb27'), ObjectId('65fa280976dd4549cca1eb28'), ObjectId('65fa280976dd4549cca1eb29'), ObjectId('65fa280976dd4549cca1eb2a'), ObjectId('65fa280976dd4549cca1eb2b'), ObjectId('65fa280976dd4549cca1eb2c'), ObjectId('65fa280976dd4549cca1eb2d'), ObjectId('65fa280976dd4549cca1eb2e'), ObjectId('65fa280976dd4549cca1eb2f'), ObjectId('65fa280976dd4549cca1eb30'), ObjectId('65fa280976dd4549cca1eb31'), ObjectId('65fa280976dd4549cca1eb32'), ObjectId('65fa280976dd4549cca1eb33'), ObjectId('65fa280976dd4549cca1eb34'), ObjectId('65fa280976dd4549cca1eb35'), ObjectId('65fa280976dd4549cca1eb36'), ObjectId('65fa280976dd4549cca1eb37'), ObjectId('65fa280976dd4549cca1eb38'), ObjectId('65fa280976dd4549cca1eb39'), ObjectId('65fa280976dd4549cca1eb3a'), ObjectId('65fa280976dd4549cca1eb3b'), ObjectId('65fa280976dd4549cca1eb3c'), ObjectId('65fa280976dd4549cca1eb3d'), ObjectId('65fa280976dd4549cca1eb3e'), ObjectId('65fa280976dd4549cca1eb3f'), ObjectId('65fa280976dd4549cca1eb40'), ObjectId('65fa280976dd4549cca1eb41'), ObjectId('65fa280976dd4549cca1eb42'), ObjectId('65fa280976dd4549cca1eb43'), ObjectId('65fa280976dd4549cca1eb44'), ObjectId('65fa280976dd4549cca1eb45'), ObjectId('65fa280976dd4549cca1eb46'), ObjectId('65fa280976dd4549cca1eb47'), ObjectId('65fa280976dd4549cca1eb48'), ObjectId('65fa280976dd4549cca1eb49'), ObjectId('65fa280976dd4549cca1eb4a'), ObjectId('65fa280976dd4549cca1eb4b'), ObjectId('65fa280976dd4549cca1eb4c'), ObjectId('65fa280976dd4549cca1eb4d'), ObjectId('65fa280976dd4549cca1eb4e'), ObjectId('65fa280976dd4549cca1eb4f'), ObjectId('65fa280976dd4549cca1eb50'), ObjectId('65fa280976dd4549cca1eb51'), ObjectId('65fa280976dd4549cca1eb52'), ObjectId('65fa280976dd4549cca1eb53'), ObjectId('65fa280976dd4549cca1eb54'), ObjectId('65fa280976dd4549cca1eb55'), ObjectId('65fa280976dd4549cca1eb56'), ObjectId('65fa280976dd4549cca1eb57'), ObjectId('65fa280976dd4549cca1eb58'), ObjectId('65fa280976dd4549cca1eb59'), ObjectId('65fa280976dd4549cca1eb5a'), ObjectId('65fa280976dd4549cca1eb5b'), ObjectId('65fa280976dd4549cca1eb5c')], acknowledged=True)